apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 30
>>>>>>> refs/remotes/origin/master
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
